name: tamil_setu
description: A Hindi-to-Tamil learning app.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  audioplayers: ^6.5.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0
  animate_do: ^4.2.0
  sign_in_button: ^4.0.1
  flutter_local_notifications: ^21.0.0-dev.2
  timezone: ^0.11.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
  golden_screenshot: ^10.0.0
  mockito: ^5.3.2
  firebase_core_platform_interface: 
  plugin_platform_interface:
  fake_cloud_firestore: ^4.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#005DAA" # Your Peacock Blue
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/data/master_content.json
    - assets/images/
  fonts:
    - family: NotoSansHindi
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
